# yaml-language-server: $schema=https://raw.githubusercontent.com/DavidAnson/markdownlint-cli2/refs/heads/main/schema/markdownlint-cli2-config-schema.json

# Uses @github/markdownlint-github configuration with overrides
config:
  # Override: disable fenced-code-language rule
  extends: "markdownlint/style/prettier"
  fenced-code-language: false
  line-length:
    line_length: 200
    heading_line_length: 120
    code_block_line_length: 120
    code_blocks: true
    tables: false # Disable line length for tables as they're often wide
    headings: true
    strict: false
    stern: false
  no-inline-html:
    allowed_elements:
      - details
      - summary
      - br
  no-emphasis-as-heading: false # Allow emphasis as headings for stylistic purposes
  no-space-in-emphasis: false # Allow spaces in emphasis markers for GitHub workflow expressions

# File type specific configurations - only run on markdown files
ignores: ["**/*.yml", "**/*.yaml", "node_modules/**"]

# Custom rules from @github/markdownlint-github
customRules:
  - "@github/markdownlint-github"

# Output formatting with pretty formatter and appendLink option
outputFormatters:
  - - "markdownlint-cli2-formatter-pretty"
    - appendLink: true
